postgresql:
  image: postgres:9.3
  environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=root
  volumes:
    - /opt/databases/postgresql/data:/var/lib/postgresql/data
  container_name: postgresql-server
  hostname: postgresql-server.dev